### ISSUE TITLE
Add offline-paging function

### ISSUE THREAD

**Issue by Hijacker** [XVMX/vmbot#47]
People who are offline cannot be messaged. Add a command which takes a user name and message and have the bot post it in the channel it was registered in as soon as the user name joins the channel. Save them in a sqlite DB so messages survive outages.

sendmsg <uname> <message>

**Comment by ThirteenFish** [comment]
I had a similar idea to this called remind that would take a time offset and a message, and would post the message once the offset had expired and the poster was in the channel. It shouldn't be too hard to merge these functions. Also having the option to message in a pm might be prudent, if nothing else but to have an especially noticeable way of getting the message across.

Something like this then:
`page [uname] [offset] [-pm] <message>`

 * `offset` probably being in a strftime() format like `%jd%Hh%Mm`
 * Without `uname` it would target the issuer of the command.
 * Without `offset` it would issue it as soon as the bot can see user `uname` 
 * This leads to the natural behaviour in the case of neither `uname` or `offset` being immediately turning around and relaying the message back to the issuer.

Also I'm undecided whether I like pm as default and public as the flag or vice versa.
